export const CURRENT_WEATHER_LOCATION_REQUEST = 'CURRENT_WEATHER_LOCATION_REQUEST'
export const CURRENT_WEATHER_LOCATION_SUCCESS = 'CURRENT_WEATHER_LOCATION_SUCCESS'
export const CURRENT_WEATHER_LOCATION_FAIL = 'CURRENT_WEATHER_LOCATION_FAIL'

export const CURRENT_LOCATION_FORECAST_REQUEST = 'CURRENT_LOCATION_FORECAST_REQUEST'
export const CURRENT_LOCATION_FORECAST_SUCCESS = 'CURRENT_LOCATION_FORECAST_SUCCESS'
export const CURRENT_LOCATION_FORECAST_FAIL = 'CURRENT_LOCATION_FORECAST_FAIL'

export const CITY_WEATHER_REQUEST = 'CITY_WEATHER_REQUEST'
export const CITY_WEATHER_SUCCESS = 'CITY_WEATHER_SUCCESS'
export const CITY_WEATHER_FAIL = 'CITY_WEATHER_FAIL'